exclude :"test_compare?", "work in progress"
exclude :test_ed25519, "work in progress"
exclude :test_generic_oid_inspect, "work in progress"
exclude :test_generic_oid_inspect_rsa, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271"
exclude :test_hmac_sign_verify, "work in progress"
exclude :test_legacy_error_classes, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271"
exclude :test_raw_initialize_errors, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271"
exclude :test_s_generate_key, "work in progress"
exclude :test_s_generate_parameters, "work in progress"
exclude :test_s_generate_parameters_with_block, "work in progress"
exclude :test_s_read_der_then_pem, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271, undefined method 'private_to_pem' for an instance of OpenSSL::PKey::RSA"
exclude :test_s_read_passphrase, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271, undefined method 'private_to_pem' for an instance of OpenSSL::PKey::RSA"
exclude :test_s_read_pem_unknown_block, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271, undefined method 'private_to_pem' for an instance of OpenSSL::PKey::RSA"
exclude :test_x25519, "work in progress"
