exclude :test_aia, "work in progress"
exclude :test_akiski, "work in progress"
exclude :test_crl_uris, "work in progress"
exclude :test_crl_uris_multiple_general_names, "work in progress"
exclude :test_crl_uris_no_uris, "work in progress"
exclude :test_eq, "work in progress"
exclude :test_extension, "work in progress"
exclude :test_inspect, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271"
exclude :test_sign_and_verify_nil_digest, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271, undefined method 'generate_key' for module OpenSSL::PKey"
exclude :test_invalid_extension, "work in progress"
exclude :test_load_file_certificate_der, "work in progress"
exclude :test_load_file_empty_pem, "work in progress"
exclude :test_load_file_fullchain_garbage, "work in progress"
exclude :test_load_file_fullchain_pem, "work in progress"
exclude :test_read_der_then_pem, "work in progress"
exclude :test_sign_and_verify_ed25519, "work in progress"
exclude :test_tbs_precert_bytes, "work in progress"
