exclude :test_ECPrivateKey, "work in progress"
exclude :test_ECPrivateKey_encrypted, "work in progress"
exclude :test_PUBKEY, "work in progress"
exclude :test_check_key, "work in progress"
exclude :test_derive_key, "TODO: OpenSSL::PKey::EC#derive not yet implemented"
exclude :test_dh_compute_key, "work in progress"
exclude :test_dsa_sign_asn1_FIPS186_3, "work in progress"
exclude :test_ec_group, "work in progress"
exclude :test_ec_key, "work in progress"
exclude :test_ec_key_new, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271, private key as well as public key are null"
exclude :test_ec_key_new_empty, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271, null curve name"
exclude :test_ec_point, "work in progress"
exclude :test_ec_point_add, "work in progress"
exclude :test_ec_point_mul, "work in progress"
exclude :test_generate, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271"
exclude :test_generate_key, "work in progress"
exclude :test_sign_verify_raw, "work in progress"
exclude :test_small_curve, "new failure with Ruby 4.0 tests, tested on MacOS, https://github.com/jruby/jruby/issues/9271, null curve name"
