language: java

sudo: false

cache:
 directories:
   - $HOME/.m2

before_install:
  - unset _JAVA_OPTIONS
  - rm ~/.m2/settings.xml
  - export MAVEN_SKIP_RC=true
  - mvn -Xmx32M -v | grep 1.7.0; if [ $? = 0 ]; then export MAVEN_OPTS="-XX:MaxPermSize=180M"; else export MAVEN_OPTS="-XX:MaxMetaspaceSize=180M -XX:CompressedClassSpaceSize=180M"; fi
  - export MAVEN_OPTS="-Xmx512M $MAVEN_OPTS"

before_script:
  - unset GEM_PATH GEM_HOME IRBRC JRUBY_OPTS
  - unset _JAVA_OPTIONS # travis/travis#8408
  - export PATH="`pwd`/bin:$PATH"
  - echo $HOME
  - echo $JAVA_OPTS
  - echo $MAVEN_OPTS

jdk:
  - openjdk7
#  - oraclejdk8

os:
  - linux

env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx560M"
    - MALLOC_ARENA_MAX=2
  matrix:
    - PHASE='-Ptest'
    - PHASE='-Prake -Dtask=test:jruby'
    - PHASE='-Prake -Dtask=test:jruby:fullint'
    - PHASE='-Prake -Dtask=test:jruby:jit'
    - PHASE='-Prake -Dtask=test:jruby:aot'
    - PHASE='-Prake -Dtask=test:mri'
    - PHASE='-Prake -Dtask=test:mri:fullint'
    - PHASE='-Prake -Dtask=test:mri:jit'
    - PHASE='-Prake -Dtask=test:slow_suites'
    - PHASE='-Prake -Dtask=test:tracing'
    - PHASE='-Prake -Dtask=spec:ji'
    - PHASE='-Prake -Dtask=spec:compiler'
    - PHASE='-Prake -Dtask=spec:compiler' JRUBY_OPTS=-Xcompile.invokedynamic
    - PHASE='-Prake -Dtask=spec:ffi'
    - PHASE='-Prake -Dtask=spec:regression'
    - PHASE='-Prake -Dtask=spec:ruby:fast'
    - PHASE='-Prake -Dtask=spec:jruby'
    - PHASE='-Prake -Dtask=spec:jrubyc'
    - PHASE='-Prake -Dtask=spec:profiler'

matrix:
  include:
    # these profile do no need to run for all JDKs
    - env: PHASE='-Pdist'
      jdk: oraclejdk8
    - env: PHASE='-Pjruby-jars'
      jdk: openjdk7
    - env: PHASE='-Pmain'
      jdk: oraclejdk8
    - env: PHASE='-Pcomplete'
      jdk: oraclejdk8
    - env: PHASE='-Posgi'
      jdk: openjdk7
    - env: PHASE='-Pj2ee'
      jdk: oraclejdk8
    # These next two started crashing on JDK7 in March 2015, possibly due to JVM issues on Travis's Docker-based env
    - env: PHASE='-Pjruby-jars,test -Dinvoker.test=extended'
      jdk: oraclejdk8
    - env: PHASE='-Pmain,test -Dinvoker.test=extended'
      jdk: oraclejdk8
    - env: PHASE='-Pjruby_complete_jar_extended -Dinvoker.skip=true'
      jdk: oraclejdk8
    - env: COMMAND=test/check_versions.sh
      jdk: oraclejdk8
    - env: PHASE='-Prake -Dtask=test:jruby:jit'
      jdk: oraclejdk9
    - env: PHASE='-Prake -Dtask=test:mri:jit'
      jdk: oraclejdk9
    - env: PHASE='-Prake -Dtask=spec:ruby:fast'
      jdk: oraclejdk9
    - env: PHASE='-Pmain'
      jdk: oraclejdk9
    - env: PHASE='-Pcomplete'
      jdk: oraclejdk9
  allow_failures:
    - env: PHASE='-Prake -Dtask=test:jruby:jit'
      jdk: oraclejdk9
    - env: PHASE='-Prake -Dtask=test:mri:jit'
      jdk: oraclejdk9
    - env: PHASE='-Prake -Dtask=spec:ruby:fast'
      jdk: oraclejdk9
    - env: PHASE='-Pmain'
      jdk: oraclejdk9
    - env: PHASE='-Pcomplete'
      jdk: oraclejdk9

install: tool/travis-install.sh
script: tool/travis-script.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true

# we are on a branch
    on_success: always
    on_failure: never

services:
  - redis-server

addons:
  apt:
    packages:
      - oracle-java9-installer
